name: Deploy Docker Image Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # El runner self-hosted debe tener acceso al Docker daemon

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Obtener versión del pom.xml
        id: get_version
        run: |
          # Obtiene la versión completa, por ejemplo "0.0.1-SNAPSHOT"
          ARTIFACT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "ARTIFACT_VERSION=$ARTIFACT_VERSION" >> $GITHUB_ENV
          
          # Generar DEPLOY_VERSION removiendo el sufijo "-SNAPSHOT"
          DEPLOY_VERSION=${ARTIFACT_VERSION/-SNAPSHOT/}
          echo "DEPLOY_VERSION=$DEPLOY_VERSION" >> $GITHUB_ENV
          
          echo "::set-output name=ARTIFACT_VERSION::$ARTIFACT_VERSION"
          echo "::set-output name=DEPLOY_VERSION::$DEPLOY_VERSION"
          echo "Versión del artifact: $ARTIFACT_VERSION, Versión para despliegue: $DEPLOY_VERSION"

      - name: Validar que la versión no esté vacía
        run: |
          if [ -z "${{ env.ARTIFACT_VERSION }}" ] || [ -z "${{ env.DEPLOY_VERSION }}" ]; then
            echo "ERROR: Una de las variables de versión está vacía."
            exit 1
          fi
          echo "Construyendo la imagen Docker con ARTIFACT_VERSION: ${{ env.ARTIFACT_VERSION }} y DEPLOY_VERSION: ${{ env.DEPLOY_VERSION }}"

      - name: Construir la imagen Docker
        run: |
          docker build --no-cache --build-arg VERSION=${{ env.ARTIFACT_VERSION }} -t gateway-service:${{ env.DEPLOY_VERSION }} .

      - name: Actualizar docker-compose.yml con la versión (usando copia temporal)
        run: |
          cp /workspace/docker-compose.yml /tmp/docker-compose.temp.yml
          sed -i "s|^\( *\)image: gateway-service:.*|\1image: gateway-service:${{ env.DEPLOY_VERSION }}|" /tmp/docker-compose.temp.yml
          cp /tmp/docker-compose.temp.yml /workspace/docker-compose.yml
          echo "Contenido actualizado de docker-compose.yml:"
          cat /workspace/docker-compose.yml

      - name: Detener y eliminar contenedor antiguo
        run: |
          docker stop gateway-service || true
          docker rm gateway-service || true

      - name: Crear y levantar el contenedor manualmente con la red correcta
        run: |
          docker run -d --name gateway-service \
            --network=deployments_backend \
            gateway-service:${{ env.DEPLOY_VERSION }}

      - name: Reconectar el contenedor a la red API (si es necesario)
        run: |
          docker network connect deployments_api gateway-service || true
      
